# Generated by Django 5.0.3 on 2024-05-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recicle360', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitacao',
            new_name='recolhe',
        ),
    ]
