# Generated by Django 5.0.3 on 2024-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recicle360', '0002_rename_solicitacao_recolhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosAbertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao_id', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
            ],
        ),
    ]
